### ISSUE TITLE
底部字体颜色没有跟着变！

### ISSUE THREAD

**Issue by dennishappy** [VictDog/YYTheme#1]
底部字体颜色没有跟着变！

**Comment by VictDog** [comment]
看了一下，是因为在AppDelegate里面设置了默认主题颜色而导致的。你将AppDelegate中[self yy_setThemeColor:[UIColor orangeColor]];这句注释掉就没问题了。

**Comment by dennishappy** [comment]
那你首次启动还是有问题啊，没加上颜色.

**Comment by VictDog** [comment]
找到YYTabBarController.m ， 将添加子控制器方法中的设置字体颜色的相关代码(setTitleTextAttributes: forState:)注释掉就可以了,  这样首次启动即使设置了主题颜色也可以正常切换颜色了。

**Comment by zzmmcxl** [comment]
如果我将YYTabBarController 的viewDidLoad 方法 [self setValue:tabBar forKeyPath:@"tabBar"];
这句话 注释后  其他所有的tabBarItem  图片的颜色都不会跟着主题的颜色变化了。
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    YYTabBar *tabBar = [YYTabBar tabBar];
    // 自定义tabBar
    //[self setValue:tabBar forKeyPath:@"tabBar"];
   
    // 设置子控制器
    [self setUpChildViewControllers];
}

**Comment by VictDog** [comment]
那是因为我在自定义的YYTabBar 内部设置的tabBar的tintColor。 如果你不想用自定义TabBar， 你只需在TabBarController 中加上 [self.tabBar yy_addToThemeColorPool:@"tintColor"];  因为你不把tintColor加到颜色池中，它是不会设置tabBar的颜色的。
